---
title: "isle"
author: "Xinge Zhang"
date: "2023-02-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# R setup
```{r setup, include=FALSE}
library(tidyverse)
library(tmap)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
library(caret)
library(yardstick)
library(pscl)
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(igraph)
library(exactextractr)
library(geojsonsf)
library(stars)
library(starsExtra)
library(mapview)
library(glue)
plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")

mv<- mapview
g <- glimpse
```



## isle_landcover
```{r}
isle_14 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/lc/islelc_14_10x10.tif")
isle_18 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/lc/islelc_18_10x10.tif")
isle_area <- st_read("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/boundary/Isle_of_Wight.shp")
# Transform the test area object to the same CRS as the raster image
isle_area <- isle_area %>% 
  st_transform(crs = st_crs(isle_14))

# Crop the re-sampled raster image to the test area
isle_14_10_crop <- st_crop(isle_14, isle_area)
isle_18_10_crop <- st_crop(isle_18, isle_area)

```


## reclass the pearmeable and impearmeable

```{r}
# Reclassify the cropped raster image
isle_14_10_rc <- isle_14_10_crop %>% 
  mutate(originallc = case_when(
    islelc_14_10x10.tif == 1  ~ 1,
    islelc_14_10x10.tif == 2 ~ 2,
    islelc_14_10x10.tif == 3 ~ 3,
    islelc_14_10x10.tif == 4 ~ 4,
    islelc_14_10x10.tif == 5 ~ 5,
    islelc_14_10x10.tif == 6 ~ 6,
    islelc_14_10x10.tif == 7 ~ 7,
    islelc_14_10x10.tif == 8 ~ 8,
    islelc_14_10x10.tif == 9 ~ 9,
    islelc_14_10x10.tif == 10 ~ 10,
    islelc_14_10x10.tif == 11  ~ 11,
    islelc_14_10x10.tif == 12 ~ 12
  ),
    lc = case_when(
    islelc_14_10x10.tif < 6  ~ 0, # permeable
    islelc_14_10x10.tif >= 6 ~ 1 # impermeable
  ))
isle_18_10_rc <- isle_18_10_crop %>% 
  mutate(
    originallc =case_when(
    islelc_18_10x10.tif == 1  ~ 1,
    islelc_18_10x10.tif == 2 ~ 2,
    islelc_18_10x10.tif == 3 ~ 3,
    islelc_18_10x10.tif == 4 ~ 4,
    islelc_18_10x10.tif == 5 ~ 5,
    islelc_18_10x10.tif == 6 ~ 6,
    islelc_18_10x10.tif == 7 ~ 7,
    islelc_18_10x10.tif == 8 ~ 8,
    islelc_18_10x10.tif == 9 ~ 9,
    islelc_18_10x10.tif == 10 ~ 10,
    islelc_18_10x10.tif == 11  ~ 11,
    islelc_18_10x10.tif == 12 ~ 12
  ),
    lc = case_when(
    islelc_18_10x10.tif < 6  ~ 0,
    islelc_18_10x10.tif >= 6 ~ 1
  ))

# Calculate the mean value for a 3x3 cell neighborhood
isle_14_pcnt_imperv = focal2(isle_14_10_rc["lc"], matrix(1, 3, 3), "mean")
isle_18_pcnt_imperv = focal2(isle_18_10_rc["lc"], matrix(1, 3, 3), "mean")
```


```{r}
#remove
rm(isle_14,isle_18)
```


## load census

```{r}
options(tigris_use_cache = TRUE)
# port
isle_tracts14 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2014, state="51", county="Isle of Wight", geometry=T, output="wide") %>%
  st_transform(st_crs(isle_14_10_rc)) %>%
  rename(TotalPop = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc = B19013_001E,
         TotalUnit = B25002_001E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop * 100,0)
         ) %>%
  dplyr::select(-Whites)

isle_tracts14[is.na(isle_tracts14)]<- 0
isle_tracts14 <-
  isle_tracts14%>%
  mutate(
         area = st_area(geometry))

isle_tracts18 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2018, state="51", county="Isle of Wight", geometry=T, output="wide") %>%
  st_transform(st_crs(isle_18_10_rc)) %>%
  rename(TotalPop = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc = B19013_001E,
         TotalUnit = B25002_001E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop * 100,0)
         ) %>%
  dplyr::select(-Whites)
isle_tracts18[is.na(isle_tracts18)]<- 0

isle_tracts18 <-
  isle_tracts18%>%
  mutate(
         area = st_area(geometry))

isle_tract <- st_join(isle_tracts14, isle_tracts18) %>%
  mutate(popchange = (TotalPop.y - TotalPop.x)/(TotalPop.x * area.x),
         pctwhitechange = (pctWhite.y - pctWhite.x),
         Unitchange = (TotalUnit.y - TotalUnit.x)/area.x,
         MedHHIncchange = (MedHHInc.y - MedHHInc.x)/area.x,
         Area = area.x,
         GEOID = GEOID.x)%>%
  dplyr::select(-ends_with(".x"),-ends_with(".y"))
```

## dem image
```{r}
dem1 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/DEM/USGS_1_n38w077_20170509.tif")
dem2 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/DEM/USGS_1_n37w077_20160315.tif")
dem <- st_mosaic(dem1, dem2)
dem2 <- st_warp(dem, crs=st_crs(isle_14_10_rc))
dem_isle <- st_crop (dem2, isle_area)
dem_isle <- st_warp(dem_isle, isle_14_10_crop)
isle_slope<- slope(dem_isle)
```

## water shed
scale is too large for analysis. Maybe can be used for later analysis
## soil

```{r}
soil <- st_read('~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/Soil/isle/isle_soil.shp', crs= 'EPSG:4326')
soilclass <- soil%>%
  mutate(soil = case_when(
    isle__Ra_1 == 'D' ~ 6,
    isle__Ra_1 == 'C' ~ 5,
    isle__Ra_1 == 'B/D' ~ 4,
    isle__Ra_1 == 'B' ~ 3,
    isle__Ra_1 == 'A/D' ~ 2,
    isle__Ra_1 == 'A' ~ 1,
    is.na(isle__Ra_1) ~ 0
  )) %>%
dplyr::select(-colnames(soil),geometry)%>%
  st_transform(st_crs(isle_14_10_rc))
  
soil_isle <- st_crop(soilclass, isle_area)
```


```{r}
rm(dem1,dem2,dem)
```

# -----testing part
```{r}
# Function to calculate focal mean
calc_focal_mean <- function(df, field, ksize) {
  focal2(df[field], matrix(1, ksize, ksize), "mean") %>%
    focal2(., matrix(1, ksize, ksize), "mean") %>%
    focal2(., matrix(1, ksize, ksize), "mean")
}

# Road
isle_14_road <- isle_14_10_crop %>%
  mutate(road = as.numeric(islelc_14_10x10.tif == 9))

isle_18_road <- isle_18_10_crop %>%
  mutate(road = as.numeric(islelc_18_10x10.tif == 9))

road_14 <- calc_focal_mean(isle_14_road, "road", 3)
road_18 <- calc_focal_mean(isle_18_road, "road", 3)

# Canopy
isle_14_canopy <- isle_14_10_crop %>%
  mutate(canopy = as.numeric(islelc_14_10x10.tif == 3))

isle_18_canopy <- isle_18_10_crop %>%
  mutate(canopy = as.numeric(islelc_18_10x10.tif == 3))

canopy_14_mean <- calc_focal_mean(isle_14_canopy, "canopy", 3)
canopy_18_mean <- calc_focal_mean(isle_18_canopy, "canopy", 3)

# Shrub
isle_14_shrub <- isle_14_10_crop %>%
  mutate(shrub = as.numeric(islelc_14_10x10.tif == 2))

isle_18_shrub <- isle_18_10_crop %>%
  mutate(shrub = as.numeric(islelc_18_10x10.tif == 2))

shrub_14_mean <- calc_focal_mean(isle_14_shrub, "shrub", 3)
shrub_18_mean <- calc_focal_mean(isle_18_shrub, "shrub", 3)

# Water
isle_14_water <- isle_14_10_crop %>%
  mutate(water = as.numeric(islelc_14_10x10.tif == 1))

isle_18_water <- isle_18_10_crop %>%
  mutate(water = as.numeric(islelc_18_10x10.tif == 1))

water_14_mean <- calc_focal_mean(isle_14_water, "water", 25)
water_18_mean <- calc_focal_mean(isle_18_water, "water", 25)

# Other
isle_14_other <- isle_14_10_crop %>%
  mutate(other = as.numeric(islelc_14_10x10.tif == 8))

isle_18_other <- isle_18_10_crop %>%
  mutate(other = as.numeric(islelc_18_10x10.tif == 8))

```


```{r}
other_14_mean <- focal2(isle_14_other["other"], matrix(1, 3, 3), "mean")
other_14_mean <- focal2(other_14_mean["other"], matrix(1, 3, 3), "mean")
other_18_mean <- focal2(isle_18_other["other"], matrix(1, 3, 3), "mean")
other_18_mean<- focal2(other_18_mean["other"], matrix(1, 3, 3), "mean")
```


## join all the data
```{r}
isle14 <-  cbind(isle_14_10_crop,canopy_14_mean, road_14, other_14_mean, shrub_14_mean, water_14_mean, isle_14_pcnt_imperv, isle_change_rc)
rm(canopy_14_mean, road_14, other_14_mean, shrub_14_mean, water_14_mean, isle_14_pcnt_imperv, isle_change_rc)

isle18 <- cbind(isle_18_10_crop, canopy_18_mean, road_18,other_18_mean, shrub_18_mean, water_18_mean,isle_18_pcnt_imperv)
rm(canopy_18_mean, road_18, other_18_mean, shrub_18_mean, water_18_mean, isle_18_pcnt_imperv)

isle_14 <- 
  st_join(isle_14_10_rc,isle_tract) %>%
  st_join(.,dem_isle)%>% # not changing
  st_join(.,isle_slope) %>%
  st_join(., soil_isle)%>% 
  st_join(.,isle_change) %>% # change land cover data
  st_join(., isle_change_rc)  # change impervious(0, 1, -1) -1 is targeted
  

isle_18 <- 
  st_join(isle_18_10_rc,isle_tract) %>%
  st_join(.,dem_isle)%>% # not changing
  st_join(.,isle_slope) %>%
  st_join(., soil_isle)
```

```{r}
rm(dem_isle,isle_slope, isle_14_10_crop, isle_14_10_rc, isle_14_canopy, isle_14_other, isle_14_road, isle_14_water, isle_18_10_crop, isle_18_10_rc, isle_18_canopy, isle_18_other, isle_18_road, isle_18_water)
```



```{r}
isle14_df <- 
  as.data.frame(isle_14) %>% 
  na.omit() %>%
  rename(originallc = islelc_14_10x10.tif ,
        terrain = USGS_1_n38w077_20170509.tif )%>%
  cbind(., isle14)
isle18_df <- 
  as.data.frame(isle_18) %>% 
  na.omit()%>%
  rename(originallc = islelc_18_10x10.tif ,
          terrain = USGS_1_n38w077_20170509.tif) %>%
  cbind(., isle18)
```



```{r}
write_stars(isle14,'Data/output/isle14.tif')
write_stars(isle18,'Data/output/isle18.tif')

```



```{r}
write.csv(isle14_df, '~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/output/isle14.csv')
write.csv(isle18_df, '~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/output/isle18.csv')
```


