---
title: "james"
author: "Shujing Yi"
date: "2023-02-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

# R setup
```{r setup, include=FALSE}
library(tidyverse)
library(tmap)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
library(caret)
library(yardstick)
library(pscl)
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(igraph)
library(exactextractr)
library(geojsonsf)
library(stars)
library(starsExtra)
library(mapview)
library(glue)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")

mv<- mapview
g <- glimpse
```


## Jame_landcover
```{r}
jame_14 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/lc/jame_51095_lc_2014/jame_51095_landcover_2014.tif")
jame_18 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/lc/jame_51095_lc_2018/jame_51095_landcover_2018.tif")
jame_area <- st_read("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/boundary/James.shp")
# Transform the test area object to the same CRS as the raster image
jame_area <- jame_area %>% 
  st_transform(crs = st_crs(jame_14))

# Resample the raster image to 10x10 cells
jame_14_10 <- st_warp(jame_14, cellsize = 10, crs = st_crs(jame_14))
jame_18_10 <- st_warp(jame_18, cellsize = 10, crs = st_crs(jame_18))

# Crop the resampled raster image to the test area
jame_14_10_crop <- st_crop(jame_14_10, jame_area)
jame_18_10_crop <- st_crop(jame_18_10, jame_area)

```

## reclass the pearmeable and impearmeable

```{r}
# Reclassify the cropped raster image
jame_14_10_rc <- jame_14_10_crop %>% 
  mutate(originallc = case_when(
    jame_51095_landcover_2014.tif  == 1  ~ 1,
    jame_51095_landcover_2014.tif == 2 ~ 2,
    jame_51095_landcover_2014.tif == 3 ~ 3,
    jame_51095_landcover_2014.tif == 4 ~ 4,
    jame_51095_landcover_2014.tif == 5 ~ 5,
    jame_51095_landcover_2014.tif == 6 ~ 6,
    jame_51095_landcover_2014.tif == 7 ~ 7,
    jame_51095_landcover_2014.tif == 8 ~ 8,
    jame_51095_landcover_2014.tif == 9 ~ 9,
    jame_51095_landcover_2014.tif == 10 ~ 10,
    jame_51095_landcover_2014.tif == 11  ~ 11,
    jame_51095_landcover_2014.tif == 12 ~ 12
  ),
    lc = case_when(
    jame_51095_landcover_2014.tif < 6  ~ 0, # permeable
    jame_51095_landcover_2014.tif >= 6 ~ 1 # impermeable
  ))
jame_18_10_rc <- jame_18_10_crop %>% 
  mutate(
    originallc =case_when(
    jame_51095_landcover_2018.tif == 1  ~ 1,
    jame_51095_landcover_2018.tif == 2 ~ 2,
    jame_51095_landcover_2018.tif == 3 ~ 3,
    jame_51095_landcover_2018.tif == 4 ~ 4,
    jame_51095_landcover_2018.tif == 5 ~ 5,
    jame_51095_landcover_2018.tif == 6 ~ 6,
    jame_51095_landcover_2018.tif == 7 ~ 7,
    jame_51095_landcover_2018.tif == 8 ~ 8,
    jame_51095_landcover_2018.tif == 9 ~ 9,
    jame_51095_landcover_2018.tif == 10 ~ 10,
    jame_51095_landcover_2018.tif == 11  ~ 11,
    jame_51095_landcover_2018.tif == 12 ~ 12
  ),
    lc = case_when(
    jame_51095_landcover_2018.tif < 6  ~ 0,
    jame_51095_landcover_2018.tif >= 6 ~ 1
  ))

# Calculate the mean value for a 3x3 cell neighborhood
jame_14_pcnt_imperv = focal2(jame_14_10_rc["lc"], matrix(1, 3, 3), "mean")
jame_18_pcnt_imperv = focal2(jame_18_10_rc["lc"], matrix(1, 3, 3), "mean")

## change
jame_change_rc <- (jame_18_10_rc - jame_14_10_rc)
```


```{r}
#remove
rm(jame_14_10,jame_18_10,jame_14,jame_18)
```


## load census

```{r}
options(tigris_use_cache = TRUE)

jame_tracts14 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2014, state="51", county="James City", geometry=T, output="wide") %>%
  st_transform(st_crs(jame_14_10_rc)) %>%
  rename(TotalPop = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc = B19013_001E,
         TotalUnit = B25002_001E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop * 100,0)
         ) %>%
  dplyr::select(-Whites)

jame_tracts14[is.na(jame_tracts14)]<- 0
jame_tracts14 <-
  jame_tracts14%>%
  mutate(
         area = st_area(geometry))


jame_tracts18 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2018, state="51", county="James City", geometry=T, output="wide") %>%
  st_transform(st_crs(jame_18_10_rc)) %>%
  rename(TotalPop = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc = B19013_001E,
         TotalUnit = B25002_001E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop * 100,0)
         ) %>%
  dplyr::select(-Whites)

jame_tracts18 <-
  jame_tracts18%>%
  mutate(
         area = st_area(geometry))

jame_tract <- st_join(jame_tracts14, jame_tracts18) %>%
  mutate(popchange = (TotalPop.y - TotalPop.x)/(TotalPop.x * area.x),
         pctwhitechange = (pctWhite.y - pctWhite.x),
         Unitchange = (TotalUnit.y - TotalUnit.x)/area.x,
         MedHHIncchange = (MedHHInc.y - MedHHInc.x)/area.x,
         Area = area.x,
         GEOID = GEOID.x)%>%
  dplyr::select(-ends_with(".x"),-ends_with(".y"))
```

## dem image
```{r}
# Read in the raster image
dem1 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/DEM/USGS_1_n38w077_20170509.tif")
dem2 <- read_stars("~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/DEM/USGS_1_n37w077_20160315.tif")
dem <- st_mosaic(dem1, dem2)
dem1 <- st_warp(dem1, crs=st_crs(jame_area))
dem_james <- st_crop (dem1, jame_area)
dem_james <- st_warp(dem_james, jame_18_10_crop)
james_slope<- slope(dem_james)

```

## soil

```{r}
soil <- st_read('~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/Soil/James/James_soil.shp', crs= 'EPSG:4326')
soilclass <- soil%>%
  mutate(soil = case_when(
    Report___8 == 'D' ~ 6,
    Report___8 == 'C' ~ 5,
    Report___8 == 'B/D' ~ 4,
    Report___8 == 'B' ~ 3,
    Report___8 == 'A/D' ~ 2,
    Report___8 == 'A' ~ 1,
    is.na(Report___8) ~ 0
  )) %>%
dplyr::select(-colnames(soil),geometry)%>%
  st_transform(st_crs(jame_14_10_rc))
  
soil_jame <- st_crop(soilclass, jame_area)
```

```{r}
rm(dem1,dem2,dem)
```

# -----testing part
```{r}
# Function to calculate focal mean
calc_focal_mean <- function(df, field, ksize) {
  focal2(df[field], matrix(1, ksize, ksize), "mean") %>%
    focal2(., matrix(1, ksize, ksize), "mean") %>%
    focal2(., matrix(1, ksize, ksize), "mean")
}

# Road
jame_14_road <- jame_14_10_crop %>%
  mutate(road = as.numeric(jame_51095_landcover_2014.tif == 9))

jame_18_road <- jame_18_10_crop %>%
  mutate(road = as.numeric(jame_51095_landcover_2018.tif == 9))

road_14 <- calc_focal_mean(jame_14_road, "road", 3)
road_18 <- calc_focal_mean(jame_18_road, "road", 3)

# Canopy
jame_14_canopy <- jame_14_10_crop %>%
  mutate(canopy = as.numeric(jame_51095_landcover_2014.tif == 3))

jame_18_canopy <- jame_18_10_crop %>%
  mutate(canopy = as.numeric(jame_51095_landcover_2018.tif == 3))

canopy_14_mean <- calc_focal_mean(jame_14_canopy, "canopy", 3)
canopy_18_mean <- calc_focal_mean(jame_18_canopy, "canopy", 3)

# Shrub
jame_14_shrub <- jame_14_10_crop %>%
  mutate(shrub = as.numeric(jame_51095_landcover_2014.tif == 2))

jame_18_shrub <- jame_18_10_crop %>%
  mutate(shrub = as.numeric(jame_51095_landcover_2018.tif == 2))

shrub_14_mean <- calc_focal_mean(jame_14_shrub, "shrub", 3)
shrub_18_mean <- calc_focal_mean(jame_18_shrub, "shrub", 3)

# Water
jame_14_water <- jame_14_10_crop %>%
  mutate(water = as.numeric(jame_51095_landcover_2014.tif == 1))

jame_18_water <- jame_18_10_crop %>%
  mutate(water = as.numeric(jame_51095_landcover_2018.tif == 1))

water_14_mean <- calc_focal_mean(jame_14_water, "water", 25)
water_18_mean <- calc_focal_mean(jame_18_water, "water", 25)

# Other
jame_14_other <- jame_14_10_crop %>%
  mutate(other = as.numeric(jame_51095_landcover_2014.tif == 8))

jame_18_other <- jame_18_10_crop %>%
  mutate(other = as.numeric(jame_51095_landcover_2018.tif == 8))

```


```{r}
other_14_mean <- focal2(jame_14_other["other"], matrix(1, 3, 3), "mean")
other_14_mean <- focal2(other_14_mean["other"], matrix(1, 3, 3), "mean")
other_18_mean <- focal2(jame_18_other["other"], matrix(1, 3, 3), "mean")
other_18_mean<- focal2(other_18_mean["other"], matrix(1, 3, 3), "mean")
```



## join all the data
```{r}
jame14 <- cbind(
                as.data.frame(canopy_14_mean)['canopy'],
                as.data.frame(road_14)['road'],
                as.data.frame(other_14_mean)['other'],
                as.data.frame(shrub_14_mean)['shrub'],
                as.data.frame(water_14_mean)['water'],
                as.data.frame(jame_14_pcnt_imperv)['lc'] %>%
                rename(imperv = lc ),
                as.data.frame(jame_change_rc)['lc']%>%
                rename(lcchange = lc )
                )

jame18 <- cbind(
                as.data.frame(canopy_18_mean)['canopy'],
                as.data.frame(road_18)['road'],
                as.data.frame(other_18_mean)['other'],
                as.data.frame(shrub_18_mean)['shrub'],
                as.data.frame(water_18_mean)['water'],
                as.data.frame(jame_18_pcnt_imperv)['lc'] %>%
                rename(imperv = lc )
                )
jame_14 <- 
  st_join(jame_14_10_rc,jame_tract) %>%
  st_join(.,dem_james)%>% # not changing
  st_join(.,james_slope) %>%
  st_join(., soil_jame)
  

jame_18 <- 
  st_join(jame_18_10_rc,jame_tract) %>%
  st_join(.,dem_james)%>% # not changing
  st_join(.,james_slope) %>%
  st_join(., soil_jame)
```

```{r}
rm(dem_jame,jame_slope, jame_14_10_crop, jame_14_10_rc, jame_14_canopy, jame_14_other, jame_14_road, jame_14_water, jame_18_10_crop, jame_18_10_rc, jame_18_canopy, jame_18_other, jame_18_road, jame_18_water)
```

```{r}
jame_14 <- readRDS( "~/Github/Precision-Forecasts-of-Land-Cover-Change/Rdata/jame_14.rds")
jame_18 <- readRDS("~/Github/Precision-Forecasts-of-Land-Cover-Change/Rdata/jame_18.rds")
```


```{r}
jame14_df <- 
  as.data.frame(jame_14[c(2:12)]) %>% 
  rename(#originallc = jame_51095_landcover_2014.tif ,
        terrain = USGS_1_n38w077_20170509.tif )%>%
  cbind(., jame14)  %>%
  na.omit() 
jame18_df <- 
  as.data.frame(jame_18[c(2:12)]) %>% 
  rename(#originallc = jame_51095_landcover_2018.tif ,
          terrain = USGS_1_n38w077_20170509.tif) %>%
  cbind(., jame18)%>%
  na.omit()
```




```{r}
saveRDS(jame14_df, "~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/output/jame14_df.rds")
saveRDS(jame18_df, "~/Github/Precision-Forecasts-of-Land-Cover-Change/Data/output/jame18_df.rds")
```


```{r}
saveRDS(jame_14,"jame_14.rds")
saveRDS(jame_18,"jame_18.rds")
```



```{r}
write_stars(jame14,'Data/output/jame14.tif')
write_stars(jame18,'Data/output/jame18.tif')

```



```{r}
write.csv(jame14_df, 'Data/output/jame14.csv')
write.csv(jame18_df, 'Data/output/jame18.csv')
```




# road

```{r}
# Reclassify the road
jame_14_road<- jame_14_10_crop %>% 
  mutate(road = case_when(
    jame_51095_landcover_2014.tif == 9  ~ 1,
    jame_51095_landcover_2014.tif != 9 ~ 0
  ))

jame_18_road <- jame_18_10_crop%>% 
  mutate(road = case_when(
    jame_51095_landcover_2018.tif == 9  ~ 1,
    jame_51095_landcover_2018.tif != 9 ~ 0
  ))

```

```{r}
road_14 <- focal2(jame_14_road["road"], matrix(1, 3, 3), "mean")
road_14 <- focal2(road_14["road"], matrix(1, 3, 3), "mean")
road_14 <- focal2(road_14["road"], matrix(1, 3, 3), "mean")
road_18 <- focal2(jame_18_road["road"], matrix(1, 3, 3), "mean")
road_18 <- focal2(road_18["road"], matrix(1, 3, 3), "mean")
road_18 <- focal2(road_18["road"], matrix(1, 3, 3), "mean")
mv(road_14)
```

```{r}
jame_14_canopy<- jame_14_10_crop %>% 
  mutate(canopy = case_when(
    jame_51095_landcover_2014.tif == 3  ~ 1,   #Tree Canopy
    jame_51095_landcover_2014.tif == 10 ~ 0.5, #Tree Canopy over Structure
    jame_51095_landcover_2014.tif == 11 ~ 0.5, #Tree Canopy over Other
    jame_51095_landcover_2014.tif == 12 ~ 0.5, #Tree Canopy over road
    !(jame_51095_landcover_2014.tif %in% c(3,10,11,12)) ~ 0
    
  ))

jame_18_canopy <- jame_18_10_crop%>% 
  mutate(canopy = case_when(
    jame_51095_landcover_2018.tif == 3  ~ 1,   #Tree Canopy
    jame_51095_landcover_2018.tif == 10 ~ 0.5, #Tree Canopy over Structure
    jame_51095_landcover_2018.tif == 11 ~ 0.5, #Tree Canopy over Other
    jame_51095_landcover_2018.tif == 12 ~ 0.5, #Tree Canopy over road
    !(jame_51095_landcover_2018.tif %in% c(3,10,11,12)) ~ 0
  ))

```



```{r}
jame_14_permeable<- jame_14_10_crop %>% 
  mutate(perm = case_when(
    jame_51095_landcover_2014.tif == 2  ~ 0.3,   #shrub
    jame_51095_landcover_2014.tif == 4 ~ 0.3, #herb
    jame_51095_landcover_2014.tif == 5 ~ 0.4, #wetland
    !(jame_51095_landcover_2014.tif %in% c(2,4,5)) ~ 0
  ))

jame_18_permeable<- jame_18_10_crop %>% 
  mutate(perm = case_when(
    jame_51095_landcover_2018.tif == 2  ~ 0.3,   #shrub
    jame_51095_landcover_2018.tif == 4 ~ 0.3, #herb
    jame_51095_landcover_2018.tif == 5 ~ 0.4, #wetland
    !(jame_51095_landcover_2018.tif %in% c(2,4,5)) ~ 0
  ))


```

```{r}
jame_14_water<- jame_14_10_crop %>% 
  mutate(water = case_when(
    jame_51095_landcover_2014.tif == 1  ~ 1,
    jame_51095_landcover_2014.tif != 1 ~ 0
  ))

jame_18_water <- jame_18_10_crop%>% 
  mutate(water = case_when(
    jame_51095_landcover_2018.tif == 1  ~ 1,
    jame_51095_landcover_2018.tif != 1 ~ 0
  ))

```


```{r}
jame_14_barren<- jame_14_10_crop %>% 
  mutate(barren = case_when(
    jame_51095_landcover_2014.tif == 6  ~ 1,
    jame_51095_landcover_2014.tif != 6 ~ 0
  ))

jame_18_barren <- jame_18_10_crop%>% 
  mutate(barren = case_when(
   jame_51095_landcover_2018.tif == 6  ~ 1,
   jame_51095_landcover_2018.tif != 6 ~ 0
  ))
```

```{r}
jame_14_structure<- jame_14_10_crop %>% 
  mutate(struct= case_when(
    jame_51095_landcover_2014.tif == 7  ~ 1,
    jame_51095_landcover_2014.tif != 7 ~ 0
  ))

jame_18_structure<- jame_18_10_crop%>% 
  mutate(struct = case_when(
    jame_51095_landcover_2018.tif == 7  ~ 1,
    jame_51095_landcover_2018.tif != 7 ~ 0
  ))
```

```{r}
jame_14_other<- jame_14_10_crop %>% 
  mutate(other= case_when(
    jame_51095_landcover_2014.tif == 8  ~ 1,
    jame_51095_landcover_2014.tif != 8 ~ 0
  ))

jame_18_other<- jame_18_10_crop%>% 
  mutate(other = case_when(
    jame_51095_landcover_2018.tif == 8 ~ 1,
    jame_51095_landcover_2018.tif != 8 ~ 0
  ))
```



```{r}
rm(dem1,dem2,dem)
```


```{r}
jame14 <- 
  st_join(jame_14_10_rc,jame_tract) %>%
  st_join(.,jame_14_barren)%>%
  st_join(.,jame_14_canopy)%>%
  st_join(.,jame_14_road)%>%
  st_join(.,jame_14_other)%>%
  st_join(.,jame_14_pcnt_imperv)%>%
  st_join(.,jame_14_permeable)%>%
  st_join(.,jame_14_structure)%>%
  st_join(.,jame_14_water)%>%
  st_join(.,dem_james)%>%
  st_join(.,james_slope) %>%
  st_join(.,jame_change)
  
jame18 <- 
  st_join(jame_18_10_rc,jame_tract) %>%
  st_join(.,jame_18_barren)%>%
  st_join(.,jame_18_canopy)%>%
  st_join(.,jame_18_road)%>%
  st_join(.,jame_18_other)%>%
  st_join(.,jame_18_pcnt_imperv)%>%
  st_join(.,jame_18_permeable)%>%
  st_join(.,jame_18_structure)%>%
  st_join(.,jame_18_water)%>%
  st_join(.,dem_james)%>%
  st_join(.,james_slope)
```


```{r}
# convert raster to sf to crop
jame_change_sf <- st_as_sf(jame_change_rc['lcp'])%>%na.omit()
# crop for analysis
jame14_crop <- st_crop(jame14, jame_change_sf%>%filter(lcp !=0))
```

```{r}
jame14_df <- 
  as.data.frame(jame14) %>% 
  na.omit() %>%
  rename(originallc = jame_51095_landcover_2014.tif,
        terrain = USGS_1_n37w077_20160315.tif )
jame18_df <- 
  as.data.frame(jame18) %>% 
  na.omit()%>%
  rename(originallc = jame_51095_landcover_2014.tif,
          terrain = USGS_1_n37w077_20160315.tif)
jamech_df <- 
  as.data.frame(jame14_crop) %>% 
  na.omit() %>%
  rename(originallc = jame_51095_landcover_2014.tif,
        terrain = USGS_1_n37w077_20160315.tif )
```

```{r fig.width=20}
tm_shape(jame_area) +
tm_fill("grey90",alpha = 0.2) +
tm_borders(col = 'grey')+
  tm_shape(jame14[c(3)],legend.only = TRUE) +
  tm_raster(palette = palette5,legend.hist = TRUE)  +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_shape(jame14[c(4)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette5,legend.hist = TRUE)  +
  tm_shape(jame14[c(5)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette5,legend.hist = TRUE)  +
   tm_shape(jame14[c(6)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette5,legend.hist = TRUE)  +
  tm_shape(jame14[c(3:6)]) +
  tm_facets(ncol = 4) +
  tm_raster(palette = palette5)  +
  tm_shape(jame_change_sf%>%filter(lcp == 1))+
  tm_bubbles(size = 0.01,alpha=0.01,col= c('#ffffcc'))+
  tm_shape(jame_change_sf%>%filter(lcp == -1))+
  tm_bubbles(size = 0.01,alpha=0.01, col= c('darkgreen'))+
tm_layout(
	inner.margins=c(.1,.1, .1,0.01),
	legend.outside.position	= "right",
	panel.labels = c('Population Change','Percentage of White Change','House Unit Change', 'Median Income change'),
  panel.label.bg.color = 'white',
	panel.label.size = 1.5

)

```

```{r fig.width=20}
tm_shape(jame_area) +
tm_fill("grey90",alpha = 0.2) +
tm_borders(col = 'grey')+
  tm_shape(jame14[c(8,11,13)]) +
  tm_legend(outside = TRUE,hist.width = 2 ,hist.height = 5) +
tm_raster(palette = palette5[c(1:3)],legend.hist = TRUE)  +
    tm_facets(ncol = 3) +
tm_layout(legend.outside.size = 0.2,
	inner.margins=c(.1,.1, .1,0.01),
  panel.labels = c('Canopy','Shrubs & Low vegetation','Water'),
	panel.label.bg.color = 'white',
	panel.label.size = 1.5,
	legend.outside.position	= "right")
```



```{r fig.width=20}
tm_shape(jame_area) +
tm_fill("grey90",alpha = 0.2) +
tm_borders(col = 'grey')+
  tm_shape(jame14[c(8,11,13)]) +
  tm_legend(outside = TRUE,hist.width = 2 ,hist.height = 5) +
tm_raster(palette = palette5[c(1:3)],legend.hist = TRUE)  +
    tm_facets(ncol = 2) +
tm_layout(legend.outside.size = 0.2,
	inner.margins=c(.1,.1, .1,0.01),
  panel.labels = c('DEM','Slope'),
	panel.label.bg.color = 'white',
	panel.label.size = 1.5,
	legend.outside.position	= "right")
```

```{r fig.width=10}
tm_shape(jame_area) +
tm_fill("#253494") +
tm_borders(col = 'grey')+
  tm_shape(jame14_crop[c(8)],legend.only = TRUE) +
  tm_raster(palette =  palette5[c(1:3)],legend.hist = TRUE)  +
  tm_legend(outside = TRUE,hist.width = 2,hist.height = 5) +
tm_layout(
	inner.margins=c(.1,.1, .1,0.01),
	legend.outside.position	= "right",

  panel.label.bg.color = 'white',
	panel.label.size = 1.5

)
```

```{r fig.width=15}
tm_shape(jame_area) +
tm_fill("#253494") +
tm_borders(col = 'grey')+
  tm_shape(jame14_crop[c(3)],legend.only = TRUE) +
  tm_raster(palette = palette10,legend.hist = TRUE)  +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_shape(jame14_crop[c(4)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette10,legend.hist = TRUE)  +
  tm_shape(jame14_crop[c(5)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette10,legend.hist = TRUE)  +
   tm_shape(jame14_crop[c(6)],legend.only = TRUE) +
  tm_legend(outside = TRUE,hist.width = 7,hist.height = 7) +
  tm_raster(palette = palette10,legend.hist = TRUE)  +
  tm_shape(jame14_crop['lcp']) +
  tm_raster(palette = palette5)  +
tm_layout(
	inner.margins=c(.1,.1, .1,0.01),
	legend.outside.position	= "right",

  panel.label.bg.color = 'white',
	panel.label.size = 1.5

)
```


```{r fig.width=20}
tm_shape(jame_area) +
tm_fill("grey90",alpha = 0.2) +
tm_borders(col = 'grey')+
  tm_shape(jame14[c(2,7,9,10,12)]) +
  tm_legend(outside = TRUE,hist.width = 2 ,hist.height = 5) +
tm_raster(palette = palette10[c(1,9)],legend.hist = TRUE)  +
    tm_facets(ncol = 5) +
tm_layout(legend.outside.size = 0.2,
	inner.margins=c(.1,.1, .1,0.01),
  panel.labels = c('Impervious Ratio','Barren','Road', 'Other Impervious','Structure','Change'),
	panel.label.bg.color = 'white',
	panel.label.size = 1.5,
	legend.outside.position	= "right")
```





