---
title: "eda"
author: "Xinge Zhang"
date: "2023-01-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, tigris_use_cache = TRUE)
```

## R Markdown

Load libary

```{r cars}
library(RColorBrewer)
library(tidyverse)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
library(caret)
library(yardstick)
library(pscl)
library(plotROC) 
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(viridis)
library(igraph)
library(ggplot2)
library(RColorBrewer)
plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- brewer.pal(2,"YlOrRd")
palette4 <- brewer.pal(4,"YlOrRd")
palette5 <- brewer.pal(5,"YlOrRd")
palette10 <- brewer.pal(10,"RdYlBu")

#this function converts a column in to quintiles. It is used for mapping.
quintileBreaks <- function(df,variable) {
    as.character(quantile(df[[variable]],
                          c(.01,.2,.4,.6,.8),na.rm=T))
}

#This function can be used to convert a polygon sf to centroids xy coords.
xyC <- function(aPolygonSF) {
  as.data.frame(
    cbind(x=st_coordinates(st_centroid(aPolygonSF))[,1],
          y=st_coordinates(st_centroid(aPolygonSF))[,2]))
} 

#this function convert a raster to a data frame so it can be plotted in ggplot
rast <- function(inRaster) {
  data.frame(
    xyFromCell(inRaster, 1:ncell(inRaster)), 
    value = getValues(inRaster)) }
```

## Landcoverdata


```{r pressure, echo=FALSE}
islelc_14 = raster("~/Github/Practicum/Data/lc/isle_51093_lc_2014/isle_51093_landcover_2014.tif")
islelc_18 = raster("~/Github/Practicum/Data/lc/isle_51093_lc_2018/isle_51093_landcover_2018.tif")
islelc_change = raster("~/Github/Practicum/Data/lc/isle_51093_lc_change_2014_2018/isle_51093_landcoverchange_20142018.tif")
jamelc_14 = raster("~/Github/Practicum/Data/lc/jame_51095_lc_2014/jame_51095_landcover_2014.tif")
jamelc_18 = raster("~/Github/Practicum/Data/lc/jame_51095_lc_2018/jame_51095_landcover_2018.tif")
jamelc_change = raster("~/Github/Practicum/Data/lc/jame_51095_lc_change_2014_2018/jame_51095_landcoverchange_20142018.tif")
portlc_14 = raster("~/Github/Practicum/Data/lc/port_51740_lc_2014/port_51740_landcover_2014.tif")
portlc_18 = raster("~/Github/Practicum/Data/lc/port_51740_lc_2018/port_51740_landcover_2018.tif")
portlc_change = raster("~/Github/Practicum/Data/lc/port_51740_lc_change_2014_2018/port_51740_landcoverchange_20142018.tif")
```

```{r}
options(tigris_use_cache = TRUE)
isle_tracts14 <- 
  get_acs(geography = "tract", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2014, state="51", county="093", geometry=T, output="wide") %>%
  st_transform('ESRI:102271') %>%
  rename(TotalPop = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc = B19013_001E,
         TotalUnit = B25002_001E,
         TotalPoverty = B06012_002E,
         TotalUnemployment =    B27011_008E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite = ifelse(TotalPop > 0, Whites / TotalPop * 100,0),
         pctPoverty = ifelse(TotalPop > 0, TotalPoverty / TotalPop *100, 0),
         pctUnemploy = ifelse(TotalPop > 0, TotalUnemployment / TotalPop *100, 0)
         ) %>%
  dplyr::select(-Whites, -TotalPoverty ,-TotalUnemployment,-GEOID)
#%>%st_transform(st_crs(chicago_fishnet)) 

isle_tracts14.MedHHInc <- isle_tracts14 %>%
  dplyr::select(MedHHInc) %>%
  rename(Legend = MedHHInc)

isle_tracts14.pctWhite <- isle_tracts14 %>%
  dplyr::select(pctWhite)%>%
  rename(Legend = pctWhite)

isle_tracts14.pctPoverty <- isle_tracts14 %>%
  dplyr::select(pctPoverty)%>%
  rename(Legend = pctPoverty)

isle_tracts14.pctUnemploy <- isle_tracts14 %>%
  dplyr::select(pctUnemploy)%>%
  rename(Legend = pctUnemploy)
```

```{r}
ggplot() +
  geom_sf(data=houstonMSA) +
  geom_raster(data=rast(lc_change) %>% na.omit %>% filter(value > 0), 
              aes(x,y,fill=as.factor(value))) +
  scale_fill_viridis(direction = -1, discrete=TRUE, name ="Land Cover\nChange") +
  labs(title = "Land Cover Change, 2000-2010") +
  mapTheme +
  theme(legend.direction="horizontal")
```

