---
title: "Land cover prediction"
author: "Yuewen Dai, Shujing Yi, Xinge Zhang"
date: "2023-01-24"
output: html_document
---

# R setup
```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
#library(QuantPsyc) # JE Note: in R 4.1, QuantPsyc package not available.
library(caret)
library(yardstick)
library(pscl)
library(plotROC) 
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(viridis)
library(igraph)
library(exactextractr)
library(geojsonsf)
library(stars)
library(starsExtra)
library(mapview)
library(glue)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")
```

```{r}
# Create an object for the mapview function
mv <- mapview

# Define the test area using a GeoJSON object
test_area_geojson <- ('{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          [
            [
              -76.39234690920298,
              36.87876463306954
            ],
            [
              -76.39234690920298,
              36.834353349364704
            ],
            [
              -76.33074641705893,
              36.834353349364704
            ],
            [
              -76.33074641705893,
              36.87876463306954
            ],
            [
              -76.39234690920298,
              36.87876463306954
            ]
          ]
        ],
        "type": "Polygon"
      }
    }
  ]
}')
```

```{r}
# Read in the raster image
pl_14 <- read_stars("Data/lc/port_51740_lc_2014/port_51740_landcover_2014.tif")

# Transform the test area object to the same CRS as the raster image
test_area <- geojson_sf(test_area_geojson, crs = "EPSG::4326") %>% 
  st_transform(crs = st_crs(pl_14))

# Resample the raster image to 10x10 cells
pl_14_10 <- st_warp(pl_14, cellsize = 10, crs = st_crs(pl_14))

# Plot the resampled raster image
mv(pl_14_10) + mv(test_area)

# Crop the resampled raster image to the test area
pl_14_10_crop <- st_crop(pl_14_10, test_area)

# Plot the cropped raster image
mv(pl_14_10_crop) + mv(test_area)



```
```{r}
# Reclassify the cropped raster image
pl_14_10_rc <- pl_14_10_crop %>% 
  mutate(lc = case_when(
    port_51740_landcover_2014.tif < 6  ~ 0,
    port_51740_landcover_2014.tif >= 6 ~ 1
  ))

# Plot the reclassified raster image
#error
xx <- pl_14_10_rc["lc"]
mv(xx)


```

```{r}
# Create a table of values for the reclassified raster image
table(pl_14_10_rc["lc"])

# Calculate the mean value for a 3x3 cell neighborhood
pcnt_imperv = focal2(pl_14_10_rc["lc"], matrix(1, 3, 3), "mean")

# histogram of the percentage of 1 (impervious) per 30x30m cell
hist(pcnt_imperv$lc)

# Plot the result of the mean calculation
# Why do these two methods look different?
plot(pcnt_imperv)
mv(pcnt_imperv)
```

```{r}
# Read in the raster image
dem1 <- read_stars("Data/DEM/USGS_1_n38w077_20170509.tif")
dem2 <- read_stars("Data/DEM/USGS_1_n37w077_20160315.tif")


```

Read the data
```{r}
isle_bound<- st_read("Data/isle/Precincts2022")%>% 
  st_transform(crs = st_crs(pl_14))

```

```{r}
# Crop the resampled raster image to the test area
dem_isle <- st_crop(dem, isle_bound)

# Plot the cropped raster image
mv(dem_isle) + mv(isle_bound)
```


```{r}
#this function converts a column in to quintiles. It is used for mapping.
quintileBreaks <- function(df,variable) {
    as.character(quantile(df[[variable]],
                          c(.01,.2,.4,.6,.8),na.rm=T))
}

#This function can be used to convert a polygon sf to centroids xy coords.
xyC <- function(aPolygonSF) {
  as.data.frame(
    cbind(x=st_coordinates(st_centroid(aPolygonSF))[,1],
          y=st_coordinates(st_centroid(aPolygonSF))[,2]))
} 

#this function convert a raster to a data frame so it can be plotted in ggplot
rast <- function(inRaster) {
  data.frame(
    xyFromCell(inRaster, 1:ncell(inRaster)), 
    value = getValues(inRaster)) }
```



```{r}
isle_2014 <- raster("Data/lc/cell_size_changed/isle_2014")
#%>%
 # crop(y = isle_bound %>% st_transform(crs(isle_2014)))
isle_2018 <- raster("Data/lc/cell_size_changed/isle_2018")
port_2014 <- raster("Data/lc/cell_size_changed/port_2014")
port_2018 <- raster("Data/lc/cell_size_changed/port_2018")
james_2014 <- raster("Data/lc/cell_size_changed/james_2014")
james_2018 <- raster("Data/lc/cell_size_changed/james_2018")

```


# Create fishnet
```{r}
isle_fishnet <- 
  st_make_grid(isle_bound,
               cellsize = 100, 
               square = FALSE) %>%
  .[isle_bound] %>%            # <- MDH Added
  st_sf() %>%
  mutate(uniqueID = rownames(.))
isle_fishnet$cellsize <- as.numeric(st_area(isle_fishnet$geometry))

 netBorder <- st_union(isle_fishnet) %>% st_as_sf()

# ggplot() +
#   geom_sf(data = isle_fishnet, fill = "black", color = "white", stroke = 0.1) +
#   labs(title = "Fishnet, xx sq.mi. area per cell",
#        subtitle = "Isle of Wight County, Virginia South") +
#   mapTheme

```

# join landcover data to fishnet
```{r}
#join the landcover data
isle_net <- cbind(isle_fishnet, exact_extract(isle_2014, 
isle_fishnet %>% st_transform(crs(isle_2014)),'mode'))%>%
rename(landcover=exact_extract.isle_2014..isle_fishnet.....st_transform.crs.isle_2014....)

isle_net <- isle_net %>%
  mutate(landcovername = case_when(landcover == "1" ~ "Water",
                               landcover == "2" ~ "Emergent Wetlands",
                               landcover == "3" ~ "Tree Canopy",
                               landcover== "4" ~ "Scrub/Shrub",
                               landcover == "5" ~ "Herbaceous",
                               landcover == "6" ~ "Barren",
                               landcover == "7" ~ "Structures",
                               landcover == "8" ~ "Other Impervious",
                               landcover == "9" ~ "Roads",
                               landcover == "10" ~ "Tree Canopy over Structures",
                               landcover == "11" ~ "Tree Canopy over Other Impervious",
                               landcover == "12" ~ "Tree Canopy over Roads")) %>%
  mutate(landcover = make.names(landcover)) %>%
  mutate(landcover = as.factor(landcover))
```

plot
```{r}
ggplot() +
  geom_sf(data = isle_net, aes(fill = landcovername), colour = NA) +
  scale_fill_manual(values = c("Water" = "#00b4d8",
                               "Roads" = "#ffffff",
                               "Other Impervious" = "#e8d1d1",
                               "Structures" = "#b50000",
                               "Barren" = "#d2cdc0",
                               "Tree Canopy" = "#85c77e",
                               "Scrub/Shrub" = "#dcca8f",
                               "Herbaceous" = "#fde9aa",
                               "Tree Canopy over Roads" = "#fbf65d",
                               "Tree Canopy over Other Impervious" = "#ca9146",
                               "Tree Canopy over Structures" = "#c8e6f8",
                               "Emergent Wetlands" = "#64b3d5")) +
  labs(title = "Land Cover in Isle County") +
  mapTheme
```

Questions:
1.Fishnet size should be different among three counties?
2.some categories take small proportion of one fishnet cell(category>9), so that these categories can't be joined to fishnet

# DEM
```{r}
DEM1 <- raster("Data/DEM/USGS_1_n38w077_20170509.tif")
DEM2 <- raster("Data/DEM/USGS_1_n37w077_20160315.tif")
DEM <- raster::merge(DEM1, DEM2)
```

```{r}
## Define the Proj.4 spatial reference 
#https://spatialreference.org/ref/epsg/2284/proj4/
newproj <- "+proj=lcc +lat_1=37.96666666666667 +lat_2=36.76666666666667 +lat_0=36.33333333333334 +lon_0=-78.5 +x_0=3500000.0001016 +y_0=999999.9998983998 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs "
DEM <- projectRaster(DEM, crs=newproj)
```


```{r}
DEM_isle <- crop(DEM, isle_bound%>% st_transform(crs(DEM)))
isle_slope <- terrain (DEM_isle, opt='slope')
```

```{r}
#join the elevation data
isle_net <- cbind(isle_net, exact_extract(DEM_isle, isle_net %>% st_transform(crs(DEM_isle)),'mean'))
isle_net%>%rename(elevation=exact_extract.DEM_isle..isle_net.....st_transform.crs.DEM_isle....)
```

```{r}
#join the slope data
isle_net <- cbind(isle_net, exact_extract(isle_slope, isle_net %>% st_transform(crs(isle_slope)),'mean'))%>%
rename(slope=exact_extract.isle_slope..isle_net.....st_transform.crs.isle_slope....)
```

```{r}
ggplot() +
  geom_sf(data = isle_net, aes(fill = elevation), colour = NA)
  labs(title = "Elevation in Isle County") +
  mapTheme
```

```{r}
ggplot() +
  geom_sf(data = isle_net, aes(fill = slope), colour = NA)
  labs(title = "Slope in Isle County") +
  mapTheme
```
# Population


```{r}
options(tigris_use_cache = TRUE)
isle_tracts14 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2014, state="51", county="093", geometry=T, output="wide") %>%
  rename(TotalPop14 = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc14 = B19013_001E,
         TotalUnit14 = B25002_001E,
         TotalPoverty = B06012_002E,
         TotalUnemployment =    B27011_008E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite14 = ifelse(TotalPop14 > 0, Whites / TotalPop14 * 100,0),
         pctPoverty14 = ifelse(TotalPop14 > 0, TotalPoverty / TotalPop14 *100, 0),
         pctUnemploy14 = ifelse(TotalPop14 > 0, TotalUnemployment / TotalPop14 *100, 0)
         ) %>%
  dplyr::select(-Whites, -TotalPoverty ,-TotalUnemployment,-GEOID)%>%
  st_transform(st_crs(isle_net)) 

```
```{r}
options(tigris_use_cache = TRUE)
isle_tracts18 <- 
  get_acs(geography = "block group", variables = c("B01003_001E","B02001_002E","B19013_001E","B25002_001E","B06012_002E","B27011_008E"), 
          year=2018, state="51", county="093", geometry=T, output="wide") %>%
  rename(TotalPop18 = B01003_001E, 
         Whites = B02001_002E,
         MedHHInc18 = B19013_001E,
         TotalUnit18 = B25002_001E,
         TotalPoverty = B06012_002E,
         TotalUnemployment =    B27011_008E) %>%
dplyr::select(-NAME, -starts_with("B")) %>% #-starts_with("B") awesome!
  mutate(pctWhite18 = ifelse(TotalPop18 > 0, Whites / TotalPop18 * 100,0),
         pctPoverty18 = ifelse(TotalPop18 > 0, TotalPoverty / TotalPop18 *100, 0),
         pctUnemploy18 = ifelse(TotalPop18 > 0, TotalUnemployment / TotalPop18 *100, 0)
         ) %>%
  dplyr::select(-Whites, -TotalPoverty ,-TotalUnemployment,-GEOID)%>%
  st_transform(st_crs(isle_net)) 

```

```{r}
isle_fishnetPopulation14 <-
  st_interpolate_aw(isle_tracts14,isle_net, extensive=TRUE) %>%
  st_drop_geometry() %>%
  as.data.frame(.) %>%
  rownames_to_column(var = "uniqueID") %>%
  left_join(isle_net %>%
              mutate(uniqueID = as.character(uniqueID)),
            ., by=c("uniqueID"='uniqueID')) %>% 
  mutate(TotalPop14 = replace_na(TotalPop14,0),
         MedHHInc14 = replace_na(MedHHInc14,0),
         TotalUnit14 = replace_na(TotalUnit14,0),
          pctWhite14 = replace_na(pctWhite14,0),
         #pctPoverty14 = replace_na(pctPoverty14,0),
         #pctUnemploy14 = replace_na(pctUnemploy14,0),
         ) 


isle_fishnetPopulation18 <-
  st_interpolate_aw(isle_tracts18,isle_net, extensive=TRUE) %>%
  st_drop_geometry() %>%
  as.data.frame(.) %>%
  rownames_to_column(var = "uniqueID") %>%
  left_join(isle_net %>%
              mutate(uniqueID = as.character(uniqueID)),
            ., by=c("uniqueID"='uniqueID')) %>% 
  mutate(TotalPop18 = replace_na(TotalPop18,0),
         MedHHInc18 = replace_na(MedHHInc18,0),
         TotalUnit18 = replace_na(TotalUnit18,0),
          pctWhite18 = replace_na(pctWhite18,0),
         #pctPoverty18 = replace_na(pctPoverty18,0),
        # pctUnemploy18 = replace_na(pctUnemploy18,0)
        )%>%
  dplyr::select(TotalPop18, MedHHInc18,TotalUnit18,  pctWhite18,#pctPoverty18, pctUnemploy18
                )

isle_pop_net <- 
  cbind(isle_fishnetPopulation14,isle_fishnetPopulation18 %>%
  st_drop_geometry()) %>%
  mutate(pop_Change = TotalPop18 - TotalPop14,
         medinc_Change = MedHHInc18 - MedHHInc14,
         unit_Change = TotalUnit18- TotalUnit14,
         wht_Change = pctWhite18 - pctWhite14,
         #poverty_Change = pctPoverty18 - pctPoverty14,
         #Unemploy_Change = pctUnemploy18 -pctUnemploy14
  )

```

```{r}
ggplot() +
  geom_sf(data = isle_net, aes(fill = pop_Change), colour = NA)
  labs(title = "pop_Change in Isle County") +
  mapTheme
```
```{r}
ggplot() +
  geom_sf(data = isle_pop_net, aes(fill = pop_Change), colour = NA)
  labs(title = "pop_Change in Isle County") +
  mapTheme
```
# Road
```{r}
isleways <-
  st_read("https://github.com/mafichman/CPLN_675/raw/main/Week_14_15/data/UGB_Chapter_data/houstonHighways.geojson") %>%
  st_transform(st_crs(houstonMSA)) %>%
  st_intersection(houstonMSA)
```

