---
title: "port&james"
author: "Yuewen Dai"
date: "2023-02-05"
output: html_document
---

# R setup
```{r setup, include=FALSE}
library(tidyverse)
library(sf)
library(raster)
library(knitr)
library(kableExtra)
library(tidycensus)
library(tigris)
library(FNN)
#library(QuantPsyc) # JE Note: in R 4.1, QuantPsyc package not available.
library(caret)
library(yardstick)
library(pscl)
library(plotROC) 
library(ggrepel)
library(pROC)
library(grid)
library(gridExtra)
library(viridis)
library(igraph)
library(exactextractr)
library(geojsonsf)
library(stars)
library(starsExtra)
library(mapview)
library(glue)

plotTheme <- theme(
  plot.title =element_text(size=12),
  plot.subtitle = element_text(size=8),
  plot.caption = element_text(size = 6),
  axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
  axis.text.y = element_text(size = 10),
  axis.title.y = element_text(size = 10),
  # Set the entire chart region to blank
  panel.background=element_blank(),
  plot.background=element_blank(),
  #panel.border=element_rect(colour="#F0F0F0"),
  # Format the grid
  panel.grid.major=element_line(colour="#D0D0D0",size=.75),
  axis.ticks=element_blank())

mapTheme <- theme(plot.title =element_text(size=12),
                  plot.subtitle = element_text(size=8),
                  plot.caption = element_text(size = 6),
                  axis.line=element_blank(),
                  axis.text.x=element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks=element_blank(),
                  axis.title.x=element_blank(),
                  axis.title.y=element_blank(),
                  panel.background=element_blank(),
                  panel.border=element_blank(),
                  panel.grid.major=element_line(colour = 'transparent'),
                  panel.grid.minor=element_blank(),
                  legend.direction = "vertical", 
                  legend.position = "right",
                  plot.margin = margin(1, 1, 1, 1, 'cm'),
                  legend.key.height = unit(1, "cm"), legend.key.width = unit(0.2, "cm"))

palette2 <- c("#41b6c4","#253494")
palette4 <- c("#a1dab4","#41b6c4","#2c7fb8","#253494")
palette5 <- c("#ffffcc","#a1dab4","#41b6c4","#2c7fb8","#253494")
palette10 <- c("#f7fcf0","#e0f3db","#ccebc5","#a8ddb5","#7bccc4",
               "#4eb3d3","#2b8cbe","#0868ac","#084081","#f7fcf0")

mv<- mapview
```

```{r}
port_14 <- read_stars("Data/lc/port_51740_lc_2014/port_51740_landcover_2014.tif")
port_18 <- read_stars("Data/lc/port_51740_lc_2018/port_51740_landcover_2018.tif")
james_14 <- read_stars("Data/lc/jame_51095_lc_2014/jame_51095_landcover_2014.tif")
james_18 <- read_stars("Data/lc/jame_51095_lc_2018/jame_51095_landcover_2018.tif")
```

```{r}
port_area <- st_read("Data/boundary/portsmouth.shp")
james_area <- st_read("Data/boundary/James.shp")
```
## Portsmouth_landcover
```{r}

# Transform the test area object to the same CRS as the raster image
port_area <- port_area %>% 
  st_transform(crs = st_crs(port_14))

# Resample the raster image to 10x10 cells
port_14_10 <- st_warp(port_14, cellsize = 10, crs = st_crs(port_14))
port_18_10 <- st_warp(port_18, cellsize = 10, crs = st_crs(port_18))
# Plot the resampled raster image
mv(port_14_10) + mv(port_area)

# Crop the resampled raster image to the test area
port_14_10_crop <- st_crop(port_14_10, port_area)
port_18_10_crop <- st_crop(port_18_10, port_area)
# Plot the cropped raster image
mv(port_area)+mv(port_14_10_crop)


```

```{r}
# Reclassify the cropped raster image
port_14_10_rc <- port_14_10_crop %>% 
  mutate(lc = case_when(
    port_51740_landcover_2014.tif < 6  ~ 0,
    port_51740_landcover_2014.tif >= 6 ~ 1
  ))
port_18_10_rc <- port_18_10_crop %>% 
  mutate(lc = case_when(
    port_51740_landcover_2018.tif < 6  ~ 0,
    port_51740_landcover_2018.tif >= 6 ~ 1
  ))
# Plot the reclassified raster image
port_lc_14 <- port_14_10_rc["lc"]
mv(port_lc_14)
port_lc_18 <- port_18_10_rc["lc"]
mv(port_lc_18)
```

```{r}
# Create a table of values for the reclassified raster image
table(port_14_10_rc["lc"])

# Calculate the mean value for a 3x3 cell neighborhood
port_14_pcnt_imperv = focal2(port_14_10_rc["lc"], matrix(1, 3, 3), "mean")
port_18_pcnt_imperv = focal2(port_18_10_rc["lc"], matrix(1, 3, 3), "mean")
# histogram of the percentage of 1 (impervious) per 30x30m cell
hist(port_14_pcnt_imperv$lc)

# Plot the result of the mean calculation
# Why do these two methods look different?
plot(port_14_pcnt_imperv)
plot(port_18_pcnt_imperv)
mv(port_14_pcnt_imperv)
mv(port_18_pcnt_imperv)
```

## James_landcover
```{r}

# Transform the test area object to the same CRS as the raster image
james_area <- james_area %>% 
  st_transform(crs = st_crs(james_14))

# Resample the raster image to 10x10 cells
james_14_10 <- st_warp(james_14, cellsize = 10, crs = st_crs(james_14))
james_18_10 <- st_warp(james_18, cellsize = 10, crs = st_crs(james_18))
# Plot the resampled raster image
mv(james_14_10) + mv(james_area)

# Crop the resampled raster image to the test area
james_14_10_crop <- st_crop(james_14_10, james_area)
james_18_10_crop <- st_crop(james_18_10, james_area)
# Plot the cropped raster image
mv(james_area)+mv(james_14_10_crop)


```

```{r}
# Reclassify the cropped raster image
james_14_10_rc <- james_14_10_crop %>% 
  mutate(lc = case_when(
    jame_51095_landcover_2014.tif < 6  ~ 0,
    jame_51095_landcover_2014.tif >= 6 ~ 1
  ))
james_18_10_rc <- james_18_10_crop %>% 
  mutate(lc = case_when(
    jame_51095_landcover_2018.tif < 6  ~ 0,
    jame_51095_landcover_2018.tif >= 6 ~ 1
  ))
# Plot the reclassified raster image
james_lc_14 <- james_14_10_rc["lc"]
mv(james_lc_14)
james_lc_18 <- james_18_10_rc["lc"]
mv(james_lc_18)
```

```{r}
# Create a table of values for the reclassified raster image
table(james_14_10_rc["lc"])

# Calculate the mean value for a 3x3 cell neighborhood
james_14_pcnt_imperv = focal2(james_14_10_rc["lc"], matrix(1, 3, 3), "mean")
james_18_pcnt_imperv = focal2(james_18_10_rc["lc"], matrix(1, 3, 3), "mean")
# histogram of the percentage of 1 (impervious) per 30x30m cell
hist(james_14_pcnt_imperv$lc)

# Plot the result of the mean calculation
# Why do these two methods look different?
plot(james_14_pcnt_imperv)
plot(james_18_pcnt_imperv)
mv(james_14_pcnt_imperv)
mv(james_18_pcnt_imperv)
```

## Import Climate Data
### Precipitation
```{r}

```